language: python

sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - pypy

env:
  - NGHTTP2=true
  - NGHTTP2=

matrix:
  exclude:
    - env: NGHTTP2=true
      python: pypy

install:
  - ".travis/install.sh"
before_script: "flake8 hpack test"
script:
  - ".travis/run.sh"
